// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class VocabPhoto extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.VocabPhoto";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		VocabPhoto_Vocab("MyFirstModule.VocabPhoto_Vocab");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public VocabPhoto(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected VocabPhoto(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject vocabPhotoMendixObject)
	{
		super(context, vocabPhotoMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, vocabPhotoMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * @deprecated Use 'VocabPhoto.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.VocabPhoto initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.VocabPhoto.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.VocabPhoto initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.VocabPhoto(context, mendixObject);
	}

	public static myfirstmodule.proxies.VocabPhoto load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.VocabPhoto.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.VocabPhoto> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.VocabPhoto.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of VocabPhoto_Vocab
	 */
	public final myfirstmodule.proxies.Vocab getVocabPhoto_Vocab() throws com.mendix.core.CoreException
	{
		return getVocabPhoto_Vocab(getContext());
	}

	/**
	 * @param context
	 * @return value of VocabPhoto_Vocab
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Vocab getVocabPhoto_Vocab(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Vocab result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.VocabPhoto_Vocab.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Vocab.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of VocabPhoto_Vocab
	 * @param vocabphoto_vocab
	 */
	public final void setVocabPhoto_Vocab(myfirstmodule.proxies.Vocab vocabphoto_vocab)
	{
		setVocabPhoto_Vocab(getContext(), vocabphoto_vocab);
	}

	/**
	 * Set value of VocabPhoto_Vocab
	 * @param context
	 * @param vocabphoto_vocab
	 */
	public final void setVocabPhoto_Vocab(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Vocab vocabphoto_vocab)
	{
		if (vocabphoto_vocab == null) {
			getMendixObject().setValue(context, MemberNames.VocabPhoto_Vocab.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.VocabPhoto_Vocab.toString(), vocabphoto_vocab.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.VocabPhoto that = (myfirstmodule.proxies.VocabPhoto) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
